modLoader = "javafml"
loaderVersion = "[44,)"
license = "MIT"
[[mods]]
modId = "sebastrnlib"
version = "${file.jarVersion}"
displayName = "Sebastrn Lib"
logoFile = "logo.png"
authors = "ItsSebastrn"
description = '''
A common lib project for Sebastrn's mods
'''
[[dependencies.sebastrnlib]]
modId = "patchouli"
mandatory = true
versionRange = "[1.19.3-78,)"
ordering = "BEFORE"
side = "BOTH"